### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by my-web-manager** [twpayne/s3-parallel-put#33]
Executing the command with an S3 bucket located in Sydney Australia (ap-southeast-1) throws an error.

root@vmd001 [/path/to/folder/test]# /path/to/folder/s3-parallel-put --bucket=vmd001 --put=add --insecure --dry-run --limit=1 .
Traceback (most recent call last):
  File "/path/to/folder/s3-parallel-put", line 420, in <module>
    sys.exit(main(sys.argv))
  File "/path/to/folder/s3-parallel-put", line 391, in main
    bucket = connection.get_bucket(options.bucket)
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 502, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 549, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 301 Moved Permanently

**Comment by IgorKirey** [comment]
Got same error.

**Comment by martgnz** [comment]
This is not addressed on the `README`, but if you look at the code there's an option to set the AWS region as `--bucket_region=YOUR_REGION`.

In my case setting it to my region, `eu-west-1`, solved the issue:

```bash
./s3-parallel-put --bucket=MY_BUCKET \
   --put=stupid
   --dry-run --limit=1
   --bucket_region=eu-west-1
   --insecure
   .
```

**Comment by uslperera** [comment]
Is it fixed yet?

**Comment by mishudark** [comment]
no yet

**Comment by Mochaka** [comment]
I found removing the following fixed it for me

`calling_format = boto.s3.connection.OrdinaryCallingFormat(),`

**Comment by nealalpert** [comment]
commenting out `calling_format = boto.s3.connection.OrdinaryCallingFormat(),` seems to result in a 400 being returned for me.  any word on a work around for this?

**Comment by nealalpert** [comment]
After some investigation we narrowed down the issue to https://github.com/mishudark/s3-parallel-put/blob/4121ccea2cd03871f6d68ba1853cf19d27f94f54/s3-parallel-put#L289

The initial connection uses `boto.s3.connect_to_region` but the child processes do not.

Swapping this line for
```
connection = boto.s3.connect_to_region(options.bucket_region,
is_secure=options.secure,
)
```
seemed to fix our issue and allow us to upload to a region other than us-east-1.

**Comment by timdau** [comment]
To use a non-default region you must specify both the `--bucket_region` and the `--host`, as follows:
`s3-parallel-put --bucket=$BUCKET  . --bucket_region=ca-central-1 --host=s3.ca-central-1.amazonaws.com`

The S3 Endpoints can be found here https://docs.aws.amazon.com/general/latest/gr/s3.html
